### ISSUE TITLE
Fix ReadMe

### ISSUE THREAD

**Issue by shivergard** [piotrooo/php-shell-framework#1]
use Psf\Interfaces*_ShellApplicationInterface_*;
use Psf\Shell;

class HelloShell extends Shell implements **ApplicationInterface**

Just : there is no ShellApplicationInterface in code - only ApplicationInterface.

Fix this in readme : I've lost 2,5h on this

**Comment by piotrooo** [comment]
Done.

BTW. why you don't make PR for this?

**Comment by shivergard** [comment]
Thank you :)

Response to BTW:
I've downloaded it as a zip , cause added to Hg repository... 
I did not clone it ... so did not a pull request ...
